baseURL = "https://Gr3ytrac3.github.io/"
languageCode = "en-us"
title = "Cyberdev | 0xSEC"
enableRobotsTXT = true
enableEmoji = false

[params]
author = "Cyberdev"
handle = "0xSEC"
description = "Offensive security researcher. Vulnerability research, kernel exploitation, reverse engineering."
organization = "The OffSec Desk"
github = "https://github.com/Gr3ytrac3"
twitter = "https://x.com/thecyberdevhq"
linkedin = "https://www.linkedin.com/in/kalu-umah-cyberdev-690421279/"
infosec = "https://infosec.exchange/@Cyberdevhq"
substack = "https://substack.com/@cyberdevhq"
blog = "https://myblog-orpin-one.vercel.app"

[markup]
[markup.highlight]
style = "monokai"
lineNos = false
noClasses = false
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
term = ["HTML"]
page = ["HTML"]
