baseURL = "https://Gr3ytrac3.github.io/"
languageCode = "en-us"
title = "Kalu | Gr3ytrac3"
enableRobotsTXT = true
enableEmoji = false

[params]
author = "Kalu"
handle = "Gr3ytrac3"
description = "Offensive security researcher. Vulnerability research, kernel exploitation, reverse engineering."
organization = "The OffSec Desk"
github = "https://github.com/Gr3ytrac3"
twitter = "https://x.com/thecyberdevhq"
linkedin = "https://linkedin.com/in/yourprofile"
infosec = "https://infosec.exchange/@Gr3ytrac3"
substack = "https://cyberdevhq.substack.com"
blog = "https://myblog-orpin-one.vercel.app"

[markup]
[markup.highlight]
style = "monokai"
lineNos = false
noClasses = false
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
term = ["HTML"]
page = ["HTML"]
